[versions]
accompanist = "0.36.0"
akdanmaku = "1.0.3"
androidsvg = "1.4"
coil = "2.7.0"
firebase-bom = "34.0.0"
geetest-sensebot = "4.4.4"
grpc = "1.73.0"
grpc-kotlin = "1.4.3"
jsoup = "1.21.1"
koin = "4.1.0"
koin-annotations = "2.1.0"
koin-compose = "4.1.0"
kotlinx-coroutines = "1.10.2"
kotlinx-serialization = "1.9.0"
#noinspection NewerVersionAvailable 3.2 新的缓存机制导致部分响应无法正常获取
ktor = "3.1.3"
ktor-jsoup = "2.3.0"
logging = "7.0.7"
lottie = "6.6.7"
material = "1.12.0"
material-symbols-compose = "1.0.1"
protobuf = "4.31.1"
qrcode = "4.5.0"
rememberPreference = "1.1.1"
slf4j-android-mvysny = "2.0.13"
slf4j-simple = "2.0.17"
vlc = "3.6.0-eap5"
zxing = "3.5.3"

[libraries]
# https://google.github.io/accompanist/
accompanist-systemuicontroller = { module = "com.google.accompanist:accompanist-systemuicontroller", version.ref = "accompanist" }

# https://github.com/KwaiAppTeam/AkDanmaku
akdanmaku = { module = "com.kuaishou:akdanmaku", version.ref = "akdanmaku" }

# https://github.com/BigBadaboom/androidsvg
androidSvg = { module = "com.caverock:androidsvg-aar", version.ref = "androidsvg" }

# https://coil-kt.github.io/coil
coil-compose = { module = "io.coil-kt:coil-compose", version.ref = "coil" }
coil-gif = { module = "io.coil-kt:coil-gif", version.ref = "coil" }
coil-svg = { module = "io.coil-kt:coil-svg", version.ref = "coil" }

# https://firebase.google.com/docs/android/setup
firebase-bom = { module = "com.google.firebase:firebase-bom", version.ref = "firebase-bom" }
firebase-analytics = { module = "com.google.firebase:firebase-analytics" }
firebase-crashlytics = { module = "com.google.firebase:firebase-crashlytics" }

# https://docs.geetest.com/sensebot/deploy/client/android
geetest-sensebot = { module = "com.geetest.sensebot:sensebot", version.ref = "geetest-sensebot" }

# https://github.com/grpc/grpc-kotlin
grpc-kotlin-stub = { module = "io.grpc:grpc-kotlin-stub", version.ref = "grpc-kotlin" }
grpc-android = { module = "io.grpc:grpc-android", version.ref = "grpc" }
grpc-okhttp = { module = "io.grpc:grpc-okhttp", version.ref = "grpc" }
grpc-protobuf = { module = "io.grpc:grpc-protobuf", version.ref = "grpc" }
grpc-protobuf-lite = { module = "io.grpc:grpc-protobuf-lite", version.ref = "grpc" }
grpc-stub = { module = "io.grpc:grpc-stub", version.ref = "grpc" }
protobuf-kotlin = { module = "com.google.protobuf:protobuf-kotlin", version.ref = "protobuf" }
protobuf-kotlin-lite = { module = "com.google.protobuf:protobuf-kotlin-lite", version.ref = "protobuf" }

# https://jsoup.org/
jsoup = { module = "org.jsoup:jsoup", version.ref = "jsoup" }

# https://insert-koin.io
koin-core = { module = "io.insert-koin:koin-core", version.ref = "koin" }
koin-android = { module = "io.insert-koin:koin-android", version.ref = "koin" }
koin-annotations = { module = "io.insert-koin:koin-annotations", version.ref = "koin-annotations" }
koin-compose = { module = "io.insert-koin:koin-androidx-compose", version.ref = "koin-compose" }
koin-compose-navigation = { module = "io.insert-koin:koin-androidx-compose-navigation", version.ref = "koin-compose" }
koin-ksp-compiler = { module = "io.insert-koin:koin-ksp-compiler", version.ref = "koin-annotations" }

# https://kotlinlang.org/docs/jvm-test-using-junit.html
kotlin-test = { module = "org.jetbrains.kotlin:kotlin-test" }

# https://github.com/Kotlin/kotlinx.coroutines
kotlinx-coroutines = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinx-coroutines" }

# https://github.com/Kotlin/kotlinx.serialization
kotlinx-serialization = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinx-serialization" }

# https://ktor.io/docs
ktor-client-cio = { module = "io.ktor:ktor-client-cio", version.ref = "ktor" }
ktor-client-content-negotiation = { module = "io.ktor:ktor-client-content-negotiation", version.ref = "ktor" }
ktor-client-core = { module = "io.ktor:ktor-client-core", version.ref = "ktor" }
ktor-client-encoding = { module = "io.ktor:ktor-client-encoding", version.ref = "ktor" }
ktor-client-okhttp = { module = "io.ktor:ktor-client-okhttp", version.ref = "ktor" }
ktor-client-serialization-kotlinx = { module = "io.ktor:ktor-serialization-kotlinx-json", version.ref = "ktor" }
ktor-client-websockets = { module = "io.ktor:ktor-client-websockets", version.ref = "ktor" }
ktor-server-cio = { module = "io.ktor:ktor-server-cio", version.ref = "ktor" }
ktor-server-core = { module = "io.ktor:ktor-server-core", version.ref = "ktor" }

# https://github.com/T-Fowl/ktor-jsoup
ktor-jsoup = { module = "com.tfowl.ktor:ktor-jsoup", version.ref = "ktor-jsoup" }

# https://github.com/MicroUtils/kotlin-logging
logging = { module = "io.github.oshai:kotlin-logging-jvm", version.ref = "logging" }

# https://airbnb.io/lottie
lottie = { module = "com.airbnb.android:lottie-compose", version.ref = "lottie" }

# https://github.com/material-components/material-components-android
material = { module = "com.google.android.material:material", version.ref = "material" }

# https://github.com/1552980358/material-symbols-compose
material-symbols-compose-annotation = { module = "com.github.1552980358.material-symbols-compose:annotation", version.ref = "material-symbols-compose" }
material-symbols-compose-ksp = { module = "com.github.1552980358.material-symbols-compose:ksp", version.ref = "material-symbols-compose" }

# https://github.com/g0dkar/qrcode-kotlin
qrcode = { module = "io.github.g0dkar:qrcode-kotlin-android", version.ref = "qrcode" }

# https://github.com/burnoo/compose-remember-preference
rememberPreference = { module = "dev.burnoo:compose-remember-preference", version.ref = "rememberPreference" }

# https://gitlab.com/mvysny/slf4j-handroid
slf4j-android-mvysny = { module = "com.gitlab.mvysny.slf4j:slf4j-handroid", version.ref = "slf4j-android-mvysny" }

# https://www.slf4j.org
slf4j-simple = { module = "org.slf4j:slf4j-simple", version.ref = "slf4j-simple" }

# https://code.videolan.org/videolan/vlc-android
vlc-android-all = { module = "org.videolan.android:libvlc-all", version.ref = "vlc" }

# https://github.com/zxing/zxing
zxing = { module = "com.google.zxing:core", version.ref = "zxing" }
